// Sample data for the dashboard
const ordersData = [
  {
    order_id: '375A8B',
    date_time: '12-12-2025 03:30 pm',
    status: 'Pending',
    customer_name: 'Abdol Khan',
    payment_method: 'Cash',
    payment_amount: '500',
    phone: '0300-4312345',
    service: 'AC Installation',
    address: 'Nishter Colony, near by nishter bazar, Lahore',
  },
  {
    order_id: '375A8B',
    date_time: '12-12-2025 03:30 pm',
    status: 'Cancel',
    customer_name: 'Abdol Khan',
    payment_method: 'Card',
    payment_amount: '1200',
    phone: '0300-4312345',
    service: 'Electrice fan repair',
    address: 'DHA phase 6 house no 123 lahore',
  },
  {
    order_id: '375A8B',
    date_time: '12-12-2025 03:30 pm',
    status: 'Pending',
    customer_name: 'Abdol Khan',
    payment_method: 'Cash',
    payment_amount: '2400',
    phone: '0300-4312345',
    service: 'Roof waterproofing',
    address: 'Gulumoto dillawar colony Lahore',
  },
  {
    order_id: '375A8B',
    date_time: '12-12-2025 03:30 pm',
    status: 'Complete',
    customer_name: 'Abdol Khan',
    payment_method: 'Cash',
    payment_amount: '1550',
    phone: '0300-4312345',
    service: 'Electrice oven repair',
    address: 'Nishter Colony, near by nishter bazar, Lahore',
  },
  {
    order_id: '375A8B',
    date_time: '12-12-2025 03:30 pm',
    status: 'Complete',
    customer_name: 'Abdol Khan',
    payment_method: 'Card',
    payment_amount: '500',
    phone: '0300-4312345',
    service: 'AC mounting and dll installing',
    address: 'PCB board Lahore',
  },
  {
    order_id: '375A8B',
    date_time: '12-12-2025 03:30 pm',
    status: 'Complete',
    customer_name: 'Abdol Khan',
    payment_method: 'Cash',
    payment_amount: '1000',
    phone: '0300-4312345',
    service: 'Door light',
    address: 'Nishote colony nearby old self medical college lahore',
  },
  {
    order_id: '375A8B',
    date_time: '12-12-2025 03:30 pm',
    status: 'Pending',
    customer_name: 'Abdol Khan',
    payment_method: 'Card',
    payment_amount: '2500',
    phone: '0300-4312345',
    service: 'CCTV installation',
    address: 'Nishter Colony, near by nishter bazar, Lahore',
  },
];

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
  module.exports = ordersData;
}
